/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.ndc.xmlsign;

public class signlibxmlsec {
  public static String prepareDataToSign(String xmlPath, String certPemPath, String unsignedXmlPath, String targetNodePath) {
    return signlibxmlsecJNI.prepareDataToSign(xmlPath, certPemPath, unsignedXmlPath, targetNodePath);
  }

  public static int finalizeSignature(String unsignedXmlPath, String base64Signature, String signedXmlPath, String targetNodePath) {
    return signlibxmlsecJNI.finalizeSignature(unsignedXmlPath, base64Signature, signedXmlPath, targetNodePath);
  }

}
